moving the handling of saved config loading so that everyon can take advantage

diff --git a/bin/environment b/bin/environment
--- a/bin/environment
+++ b/bin/environment
@@ -47,7 +47,6 @@ NGINX_PIDFILE=${RUN_DIR}/nginx.pid
 NGINX_CONF_ROOT=${GENERATED_CONF_DIR}/nginx
 NGINX_CONF_LINK=${GENERATED_CONF_DIR}/nginx/nginx.conf
 NGINX_CONF_FILE=${GENERATED_CONF_DIR}/nginx/nginx.conf
-NGINX_PORT=9090
 
 mkdir -p ${GENERATED_CONF_DIR}
 mkdir -p ${INSTANCE_GROUP_ROOT}
@@ -58,5 +57,25 @@ mkdir -p ${TEMP_DIR}
 mkdir -p ${PERP_BASE}
 mkdir -p ${LOG_DIR}
 mkdir -p ${RUN_DIR}
+mkdir -p ${CONF_ROOT}
+
+# conveniently we allow for storing off the last used configuration to allow
+# for subsequent starts to be called without any parameters
+# so if configuration data was not provided, we'll go ahead and load
+# for clarity, we will use the saved configuration if it exists if any of
+# the config values are missing (REPO_URL, NGINX_PORT, NUM_INSTANCES)
+if [ -z "${REPO_URL}" -o -z "${NGINX_PORT}" -o -z "${NUM_INSTANCES}" ]; then
+  debug "using saved configuration"
+  if [ ! -e ${LATEST_CONF} ]; then
+    log "unable to find configuration information"
+    exit 11111
+  fi
+  source ${LATEST_CONF}
+fi
+
+# save our settings for use in the future
+echo "export REPO_URL=${REPO_URL? Missing REPO_URL, something is wrong}" > ${LATEST_CONF}
+echo "export NGINX_PORT=${NGINX_PORT? Missing NGINX_PORT, something is wrong}" >> ${LATEST_CONF}
+echo "export NUM_INSTANCES=${NUM_INSTANCES? Missing NUM_INSTANCES, something is wrong}" >> ${LATEST_CONF}
 
 ENVIRONMENT_SOURCED=1
