mo changes

diff --git a/bin/environment b/bin/environment
--- a/bin/environment
+++ b/bin/environment
@@ -3,6 +3,17 @@ silent_pushd(){ pushd $1 > /dev/null 2>&1; }
 silent_popd(){ popd $1 > /dev/null 2>&1 ; }
 log(){ echo $1 >&2; }
 
+bail_on_error(){
+  ERROR_CODE=$?
+  MESSAGE=$1
+  if [ 0 -ne ${ERROR_CODE} ]; then
+    if [ -n "${MESSAGE}" ]; then
+      echo "Error (${ERROR_CODE}): ${MESSAGE}"
+    fi
+    exit ${ERROR_CODE}
+  fi
+}
+
 ROOT=${APPROUTER_ROOT}
 MANAGED_ROOT=${ROOT}/managed
 APPROUTER_BIN_DIR=${ROOT}/bin
