stuff 'n' things

diff --git a/bin/get_git_current_sha b/bin/get_git_current_sha
--- a/bin/get_git_current_sha
+++ b/bin/get_git_current_sha
@@ -1,11 +1,11 @@
 #! /usr/bin/env bash
 REPO_DIR=${1?You must provide a repository direcory}
 if [ ! -d "$REPO_DIR" ]; then
-  echo "could not find repository directory ${REPO_DIR}"
+  echo "could not find repository directory ${REPO_DIR}" >&2
   exit 101
 fi
 if [ ! -d "${REPO_DIR}/.git" ]; then
-  echo "This doesn't appear to be the root of a git repository"
+  echo "This doesn't appear to be the root of a git repository" >&2
   exit 103
 fi
 
@@ -13,7 +13,7 @@ pushd $REPO_DIR > /dev/null
 REPO_SHA=`git log -1 --oneline | awk '{ print $1 }'`
 
 if [ -z "${REPO_SHA}" ]; then
-  echo "could find no origin url, is ${REPO_DIR} really a git repository"
+  echo "could find no origin url, is ${REPO_DIR} really a git repository" >&2
   exit 102
 fi
 
diff --git a/bin/get_git_origin_url b/bin/get_git_origin_url
--- a/bin/get_git_origin_url
+++ b/bin/get_git_origin_url
@@ -1,18 +1,19 @@
 #! /usr/bin/env bash
 REPO_DIR=${1?You must provide a repository direcory}
 if [ ! -d "$REPO_DIR" ]; then
-  echo "could not find repository directory ${REPO_DIR}"
+  echo "could not find repository directory ${REPO_DIR}" >&2
   exit 101
 fi
 if [ ! -d "${REPO_DIR}/.git" ]; then
-  echo "This doesn't appear to be the root of a git repository"
+  echo "This doesn't appear to be the root of a git repository" >&2
   exit 103
 fi
 
 pushd $REPO_DIR > /dev/null
+
 ORIGIN_URL=`git config -l | grep remote.origin.url | sed -e s[remote.origin.url=[[g`
 if [ -z "$ORIGIN_URL" ]; then
-  echo "could find no origin url, is ${REPO_DIR} really a git repository"
+  echo "could find no origin url, is ${REPO_DIR} really a git repository" >&2
   exit 102
 fi
 
